name: Deploy to GitHub Pages

on:
  push:
    branches: [ actions-demo ]  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
      
      - name: Git Credencials 
        run: git config --global user.email "abhishek.wadalkar1.com" && git config --global user.name "awadalkar1"
        
      - name: Build and Deploy for production
        env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run gh-pages

